version: "3.9"

services:
  # crawler:
  #   container_name: crawler
  #   image: jd-crawler:latest
  #   restart: always
  #   networks:
  #     - jdcrawler
  loki:
    container_name: loki
    image: grafana/loki
    restart: always
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./loki/loki.yaml:/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - jdcrawler
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana-enterprise
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - 3002:3000
    networks:
      - jdcrawler

networks:
  jdcrawler:
